---
version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
jobs:
  bundle:
    parameters:
      ruby_version:
        type: string
        default: 2.5.5
      bundler_version:
        type: string
        default: 1.17.3
      rails_version:
        type: string
        default: '5.2.2'
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - samvera/cached_checkout
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: noid-rails
      - persist_to_workspace:
          root: ~/
          paths:
          - project/*
          - project/**/*
  lint:
    parameters:
      ruby_version:
        type: string
        default: 2.5.5
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    steps:
      - attach_workspace:
          at: ~/
      - samvera/rubocop

workflows:
  version: 2
  ci:
    jobs:
      - bundle:
          ruby_version: "2.5.5"
          rails_version: "5.1.7"
      - lint:
          ruby_version: "2.5.5"
          requires:
            - bundle

